### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by corny**

### CODE REVIEW

**Comment by nicolai86** [comment]
Thank you so much @corny ! I’ll take a look later today to verify and merge the change (travis seems unhappy)

**Comment by corny** [comment]
Hey nicolai, Travis sucks a lot. Currently I am migrating my open source projects to Circle CI. It offers many up-to-date docker containers.

**Comment by corny** [comment]
Let's move to CircleCI. Tests are running like a charm.

**Comment by nicolai86** [comment]
While I think "travis sucks a lot" is not a good argument to make I'm fine switching to CircleCI.

**Comment by nicolai86** [comment]
LGTM

**Comment by nicolai86** [comment]
thanks for this improvement, @corny

**Pull request merged**
